
import React from 'react';
import { Volume2, Play, Pause, Download } from 'lucide-react';
import { Button } from '../ui/button';
import { Progress } from '../ui/progress';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';

interface AudioPlayerProps {
  isPlaying: boolean;
  onTogglePlayback: () => void;
  currentTime: number;
  duration: number;
  formatTime: (seconds: number) => string;
}

export const AudioPlayer = ({ isPlaying, onTogglePlayback, currentTime, duration, formatTime }: AudioPlayerProps) => {
  return (
    <Card className="bg-gray-900 border-gray-700">
      <CardHeader>
        <CardTitle className="text-white flex items-center gap-2">
          <Volume2 size={20} />
          Audio Overview
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="mb-6 p-4 bg-gray-800 rounded-lg">
          <div className="flex items-center justify-center h-24 mb-4">
            <Volume2 size={48} className="text-yellow-500" />
          </div>
          <div className="flex items-center gap-4">
            <Button
              onClick={onTogglePlayback}
              size="icon"
              className="bg-yellow-500 text-black hover:bg-yellow-600"
            >
              {isPlaying ? <Pause size={20} /> : <Play size={20} />}
            </Button>
            <div className="flex-1">
              <div className="flex justify-between text-sm text-gray-400 mb-1">
                <span>{formatTime(currentTime)}</span>
                <span>{formatTime(duration)}</span>
              </div>
              <Progress 
                value={(currentTime / duration) * 100} 
                className="h-2"
              />
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="text-gray-400 hover:text-white"
            >
              <Download size={16} />
            </Button>
          </div>
        </div>

        <div className="flex items-center justify-between p-4 bg-gray-800 rounded-lg">
          <div>
            <h3 className="font-medium text-white mb-1">Website Audio Summary</h3>
            <p className="text-sm text-gray-400">Generated by Google Notebook LM</p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="border-gray-600 text-gray-300">
              0.5x
            </Button>
            <Button variant="outline" size="sm" className="border-yellow-500 text-yellow-500">
              1x
            </Button>
            <Button variant="outline" size="sm" className="border-gray-600 text-gray-300">
              1.5x
            </Button>
            <Button variant="outline" size="sm" className="border-gray-600 text-gray-300">
              2x
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
